services:
    db-clean-arch:
        container_name: clean-arch
        image: postgres:latest
        environment: 
            POSTGRES_DB: 'cleanarchdb'  
            POSTGRES_PASSWORD: 'root'
            POSTGRES_USER: 'root'
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - clean-arch-server

volumes:
    pgdata:
        driver: local

networks:
    clean-arch-server:
        driver: bridge